# Generated by Django 6.1 on 2026-08-21 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaEducativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesion', models.CharField(choices=[('S1', 'Sesión 1: Mitos vs Realidades'), ('S2', 'Sesión 2: Preguntas Clave'), ('S3', 'Sesión 3: Verdadero o Falso')], max_length=2, verbose_name='Sesión')),
                ('enunciado', models.TextField(verbose_name='Pregunta o Mito')),
                ('respuesta_correcta', models.BooleanField(default=True, verbose_name='¿Es Verdadero/Realidad?')),
                ('explicacion_medica', models.TextField(help_text='Justificación redactada por el especialista', verbose_name='Explicación Médica')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pregunta Educativa',
                'verbose_name_plural': 'Preguntas Educativas',
            },
        ),
        migrations.CreateModel(
            name='AnalisisEcografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_original', models.ImageField(upload_to='imagenes_mamarias/', verbose_name='Imagen Mamaria')),
                ('mapa_gradcam', models.ImageField(blank=True, null=True, upload_to='gradcam/', verbose_name='Mapa de Calor (Grad-CAM)')),
                ('porcentaje_riesgo', models.FloatField(verbose_name='Porcentaje de Riesgo (%)')),
                ('rango_alerta', models.CharField(max_length=20, verbose_name='Nivel de Alerta')),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Análisis de Imagen Mamaria',
                'verbose_name_plural': 'Análisis de Imágenes Mamarias',
            },
        ),
    ]
